# Generated by Django 4.2.7 on 2026-08-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('warehouses', '0001_initial'),
        ('inventory', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('to_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('to_city', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=100)),
                ('to_district', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('warehouse_to_customer', 'Warehouse to Customer'), ('warehouse_to_warehouse', 'Warehouse to Warehouse'), ('supplier_to_warehouse', 'Supplier to Warehouse'), ('return', 'Return')], default='warehouse_to_customer', max_length=30)),
                ('transport_type', models.CharField(choices=[('lorry', 'Lorry'), ('bike', 'Bike'), ('car', 'Car'), ('train', 'Train'), ('ship', 'Ship'), ('air', 'Air'), ('other', 'Other')], max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='in_transit', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='fleet.deliverypartner')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='warehouses.warehouse')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['to_state', 'movement_date'], name='stock_movem_to_stat_261466_idx'), models.Index(fields=['to_city', 'movement_date'], name='stock_movem_to_city_bb3b5e_idx')],
            },
        ),
    ]
