# Generated by Django 4.2.7 on 2026-08-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('total_orders', 'Total Orders'), ('total_deliveries', 'Total Deliveries'), ('revenue', 'Revenue'), ('delivery_time', 'Average Delivery Time'), ('partner_performance', 'Partner Performance')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', 'date'], name='analytics_d_metric__3d49bc_idx'), models.Index(fields=['state', 'metric_type'], name='analytics_d_state_84b613_idx')],
            },
        ),
    ]
